### ISSUE TITLE
Add support for detecting a distro from a rootfs even on another OS

### ISSUE THREAD

**Issue by pombredanne** [python-distro/distro#161]
I would be interested to run a distro detection based on some rootfs-like archive for aLinux distro and that on any OS. It could be a a plain pre-imaged rootfs, a container image, a VM image or similar and I would like to detect what it is regardless of which OS `distro` runs on.

**Comment by pombredanne** [comment]
So essentially I would modify distro to accept an optional path to the root of a distro FS defaulting to `/` so the behavior would be the same as today by default and would not attempt to run `lsb_release` unless the path is the default '/' and the current OS is Linux.

**Comment by pombredanne** [comment]
... and make a few paths relative to that provide root path rather than absolute.
Do you have any appetite for including this type of behavior?

**Comment by nir0s** [comment]
Well, you're the first only asking for such behavior, so I can't say that I've had any appetite for it just yet. It went through my mind that it would be nice to support remote distro identification in the sense that you could just provide a machine to identify a distribution on.

**Comment by pombredanne** [comment]
perfect. I will consider a PR .

**Comment by hartwork** [comment]
`lsb_release` does not seem to support a custom root directory. So for the callto `lsb_release -a` (https://github.com/nir0s/distro/blob/1a7d01b095f757754b511591ebe428bd57e19d34/distro.py#L917) it seems to me that root permissions and using `chroot` would be needed. Unless the call to `lsb_release` can be avoided. I'm curious what you come up with.

**Comment by pombredanne** [comment]
@hartwork What is `lsb_release`?  it depends! 

This is a spec AFAIK. Tool-wise we have many implementations.

At https://sourceforge.net/projects/lsb and now at http://bzr.linuxfoundation.org/loggerhead/lsb/3.1/si/annotate/head:/lsb_release/src/lsb_release this is a shell script.

In Debian and Ubuntu this is a Python script:
https://anonscm.debian.org/cgit/collab-maint/lsb.git/tree/lsb_release.py
http://packages.ubuntu.com/yakkety/lsb-release


In Fedora and Red Hat, the lsb shell script is used as a base:
http://pkgs.fedoraproject.org/repo/extras/redhat-lsb/redhat-lsb-4.1-1.tar.bz2/9c1e474cb81c0ee1941c3129e0e50ea1/

AFAIK, other distros each use their own minor variations or do not have it at all.


So the strategy could be:
1. skip running `lsb_release` entirely.
2. OR vendor the major distros scripts and patch them to accept a root path (or something similar such as https://github.com/likema/lsb_release_ex )
3. OR implement the strategies of every `lsb_release` for distros supported here (which is essentially what this module does already so it would just be to further this)

**Comment by nir0s** [comment]
Assuming that we (we being the world) want to standardize retrieving the linux distrubtion information, I guess that not using `lsb_release` at all but rather implementation the major distribution's implementation of `lsb_release` (whatever is not already explicitly implemented in distro) would be great. This would not only force standardization but also remove a known yet arbitrarily implemented dependency on `lsb_release`.

**Comment by pombredanne** [comment]
I pushed a PR with a fix for this https://github.com/nir0s/distro/pull/247

**Comment by hartwork** [comment]
Is this ready to be closed as fixed by #247?

**Comment by HorlogeSkynet** [comment]
Indeed, closing here then 👍
