### ISSUE TITLE
Any equivalent of platform.machine?

### ISSUE THREAD

**Issue by tkdchen** [python-distro/distro#226]
As per title. If no, is there any plan to support that? Thanks.

**Comment by pombredanne** [comment]
@tkdchen what problems do you have with the current platform.machine() ?

**Comment by nir0s** [comment]
@tkdchen I second the question :)

**Comment by tkdchen** [comment]
Sorry for late response. I worked on a project that calls `platform.machine()` to detect the arch. IIRC, at that time, I probably thought it could be helpful to use distro to suppress warnings from `platform`.

**Comment by adamjstewart** [comment]
If you're looking for more detailed information than `x86_64`, you can also check out https://github.com/archspec/archspec, which returns the specific microarchitecture you are on (sandybridge, haswell, broadwell, etc.)

**Comment by sethmlarson** [comment]
I'm going to close this as it seems this functionality is implemented way better by another project.

**Comment by kdeldycke** [comment]
FYI, I also implemented another alterntive to detect [architectures in Extra Platforms](https://kdeldycke.github.io/extra-platforms/architectures.html).

So you can do:
```pycon
>>> from extra_platforms import X86_64
>>> X86_64
Architecture(id='x86_64', name='x86-64 (AMD64)')
>>> X86_64.id
'x86_64'
>>> X86_64.current
True
>>> X86_64.info()
{'id': 'x86_64', 'name': 'x86-64 (AMD64)', 'icon': '💻', 'url': 'https://en.wikipedia.org/wiki/X86-64', 'current': True, 'machine': None, 'processor': None}
```
```pycon
>>> from extra_platforms import is_x86_64
>>> is_x86_64()
True
```
