### ISSUE TITLE
Oracle Linux not always recognized properly

### ISSUE THREAD

**Issue by wiggin15** [python-distro/distro#239]
I have several versions of Oracle Linux, but `distro` doesn't recognize all of them correctly.

**Oracle Linux 5.11**
```
host-ci087 (Oracle 5.11) ➜  ~ python -c "import distro; print distro.linux_distribution()"
(u'EnterpriseEnterpriseServer', u'5.11', u'Carthage')

host-ci087 (Oracle 5.11) ➜  ~ lsb_release -a
LSB Version:	:core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	EnterpriseEnterpriseServer
Description:	Enterprise Linux Enterprise Linux Server release 5.11 (Carthage)
Release:	5.11
Codename:	Carthage
```
I guess we should fix `NORMALIZED_LSB_ID` by adding `'enterpriseenterpriseserver': 'oracle'`.
I think it has always been `EnterpriseEnterpriseServer` and not `EnterpriseEnterprise` like we already have in `NORMALIZED_LSB_ID`, but I don't have older versions to test against.

**Oracle Linux 6.1**
```
host-ci089 (Oracle 6.1) ➜  ~  python -c "import distro; print distro.linux_distribution()"
(u'Red Hat Enterprise Linux Server', u'6.1', u'Santiago')

host-ci089 (Oracle 6.1) ➜  ~  lsb_release -a
command not found: lsb_release

host-ci089 (Oracle 6.1) ➜  ~  cat /etc/oracle-release
Oracle Linux Server release 6.1
```
`lsb_release` is gone and `/etc/os-release` isn't there either but we should be able to identify that this is Oracle by reading `/etc/oracle-release`. The problem is that the files `/etc/centos-release` and `/etc/redhat-release` are there as well, and take precedence when sorted.
```
host-ci089 (Oracle 6.1) ➜  ~  cat /etc/centos-release
Red Hat Enterprise Linux Server release 6.1 (Santiago)
host-ci089 (Oracle 6.1) ➜  ~  cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.1 (Santiago)
```

**Oracle Linux 6.10 and 7.x**
These versions work fine by reading `/etc/os-release`. One remark though: the comment on `NORMALIZED_OS_ID` says `ol` means `Oracle Enterprise Linux`, but this old name was dropped since Oracle Linux 5 (including) so the versions that have `/etc/os-release` and the `ol` ID are already called by the new name, "Oracle Linux", and are not "Oracle Enterprise Linux".

**Comment by wiggin15** [comment]
The lsb_release ID in Oracle Enterprise Linux 4 seems to have been `EnterpriseEnterpriseAS` (presumably, after "RedHat Enterprise AS" - "AS" apparently meaning "Advanced Server"). I saw some bash scripts trying to match the lsb ID with `EnterpriseEnterprise*`, maybe this is where the original constant came from.

**Comment by rcorre** [comment]
The [docs](https://distro.readthedocs.io/en/latest/#distro.id) suggest that oracle linux will return "oracle" for ID, but I'm getting `ol` on oracle 7:

```
>>> import distro
>>> distro.linux_distribution()
(u'Oracle Linux Server', u'7.8', '')
>>> distro.linux_distribution(False)
(u'ol', u'7.8', '')

# uname -a
Linux oracle-7.6 4.14.35-1902.301.1.el7uek.x86_64 #2 SMP Tue Mar 31 16:50:32 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Do the docs need to be updated? I'm not 100% sure I understand @wiggin15's comment about the name being dropped, or what the expected output is here.

**Comment by wiggin15** [comment]
@rcorre to clarify my comment, Oracle renamed their product from "Oracle Enterprise Linux" to "Oracle Linux" since version 5 (including). The code included a comment next to the string `ol` that said this refers to "Oracle Enterprise Linux" even though it referred to the new name, "Oracle Linux". This comment was fixed in #250. In any case, `distro` should return `oracle` for all versions. This ticket is still open because Oracle Linux 6.1 still returns the wrong information (distro will think it is redhat). There may be other versions that have problems, but if I recall correctly I never saw this behavior. Could be something new in version 7.8.

**Comment by rcorre** [comment]
Should I open a separate ticket for 7 returning `ol` instead of `oracle`?
I also just realized that `uname` says `7.6` but distro shows `7.8` 🤔 . Not a problem for my use case but it is a little weird ...

**Comment by wiggin15** [comment]
As far as I can tell, Oracle 7.8 is still in beta, so this might explain problems like `uname` reporting a wrong version. Maybe it's better to wait for GA to see if distro still reports `ol` incorrectly?
(I'll let @nir0s decide whether this needs a separate ticket or not)

**Comment by rcorre** [comment]
Hi @HorlogeSkynet -- I don't have an Oracle machine handy to test this at the moment, but you can feel free to close. We just added a mapping on top of `distro` to normalize things:

```
{
    "redhat": "Red Hat",
    "rhel": "Red Hat",  # https://github.com/nir0s/distro/issues/36
    "oracle": "Oracle Linux Server",
    "ol": "Oracle Linux Server",  # https://github.com/nir0s/distro/issues/239
    "amazon": "Amazon Linux",
    "amzn": "Amazon Linux",  # https://github.com/nir0s/distro/issues/252
}
```

**Comment by HorlogeSkynet** [comment]
By "we" you mean your team on a local copy of `distro` ? If so, would you mind propose your changes as a PR over here ?
Thanks for your response 🙇

**Comment by HorlogeSkynet** [comment]
Fair enough, thanks again for your feedback. We'll be closing here then, one should re-open this if they think it's still an issue nowadays.
Bye 👋
