### ISSUE TITLE
Add support for AIX

### ISSUE THREAD

**Issue by jokurz** [python-distro/distro#241]
Add support for AIX. Currently disto returns the following for a AIX 7.2:
```json
{
    "codename": "",
    "id": "aix",
    "like": "",
    "version": "2",
    "version_parts": {
        "build_number": "",
        "major": "2",
        "minor": ""
    }
}
```
Source could be cmd `oslevel`:
```bash
$ oslevel
7.2.0.0
```
`7` --> major
`2` --> minor

**Comment by nir0s** [comment]
Can you share the release file?

**Comment by jokurz** [comment]
As far as I know there is no release file on AIX.

**Comment by nir0s** [comment]
There must be something.. lsb.. something.. otherwise how would distro know that it's aix?

**Comment by jokurz** [comment]
It seems that this information was gathered from `uname -rs`:
```shell
$ uname -rs
AIX 2
```

**Comment by HorlogeSkynet** [comment]
Hey @jokurz, would it be possible to read these version components from a file instead of calling `oslevel` ? Thanks 🙇

**Comment by jokurz** [comment]
@HorlogeSkynet - I am not aware of such a file. I would fully understand if you will not support AIX as the platform might not be the first choice for python development.

**Comment by HorlogeSkynet** [comment]
@jokurz thanks for your fast feedback ! We'll do our best to support (and maintain) what `distro` should.
I was asking about a specific "release" file, as sourcing such would be faster than calling another external program. Do you know a substitute for Linux `strace` command that you could run against `oslevel` to see what it does ? Bye 👋

**Comment by nir0s** [comment]
@HorlogeSkynet, while I agree that a file would be nicer, I think that we can simply try to execute oslevel as a last resort (assuming nothing else is found, e.g. release file, uname, etc..).

If that's the case, it won't cost anything, as oslevel will indeed only run when no other option is available (supposedly, only on AIX, AFAIK).

**Comment by HorlogeSkynet** [comment]
@nir0s Unless I'm missing something here, I don't think it would be that easy as `uname -rs` output is definitely working (see https://github.com/python-distro/distro/issues/241#issuecomment-494372838) 🙄

**Comment by nir0s** [comment]
Hehe, I'm the one missing something. I didn't read the previous comments.

**Comment by HorlogeSkynet** [comment]
@nir0s @jokurz So it looks like we _could_ be doing something like that in `version` method (**naive pseudo-code** here, implementation must be tougher and tests being written of course) :

```python
    def version(self, pretty: bool = False, best: bool = False) -> str:
        versions = [
            # current existing candidates list...
        ]
        if sys.platform.startswith('aix'):
            versions.insert(0, check_output("oslevel"))
```

---

@jokurz Homework chores if you don't mind :

* verify that somehow we cannot retrieve `oslevel` output another way ;
* check whether passing a specific flag to `oslevel` would be relevant in our case, according to AIX's terminology ([manual](https://www.ibm.com/docs/en/aix/7.2?topic=o-oslevel-command#d8137e99)).

---

Thanks, bye 👋

**Comment by nir0s** [comment]
@HorlogeSkynet, sounds good. However, while I don't know AIX, it doesn't make sense to me that there isn't a file with that info? Does AIX have a magical way of storing this info that we can't read?

**Comment by HorlogeSkynet** [comment]
Closing here, please see #311.
An official review is expected from you @nir0s, but I'd be interested from yours too @jokurz. Bye :wave:
