### ISSUE TITLE
Codename of Trisquel Flidas should be lowercase "flidas"

### ISSUE THREAD

**Issue by ian-kelling** [python-distro/distro#242]
```
$ distro
Name: Trisquel GNU/Linux Flidas (8.0)
Version: 8.0 (Flidas)
Codename: Flidas

$ cat /etc/os-release 
NAME="Trisquel GNU/Linux"
VERSION="8.0, Flidas"
ID=trisquel
ID_LIKE=debian
PRETTY_NAME="Trisquel GNU/Linux Flidas (8.0)"
VERSION_ID="8.0"
HOME_URL="https://trisquel.info/"
SUPPORT_URL="https://trisquel.info/wiki"
BUG_REPORT_URL="https://trisquel.info/project/issues"

$ cat /etc/apt/sources.list.d/flidas.list
deb http://mirror.fsf.org/trisquel/ flidas main
```

**Comment by nir0s** [comment]
I fail to see why it should be lowercase. It isn't written in lowercase in the release file.

It would be inconsistent with the current implementation, as we currently provide the code name as is. 

If you intend to say that all code names should be lowercase, that's a different issue and should be discussed in a wider context.

**Comment by HorlogeSkynet** [comment]
Hey @ian-kelling, it looks like Trisquel's OS-RELEASE file does not honor `VERSION_CODENAME` [1] attribute.

As `distro` does not perform distribution codenames normalization, nor special cases handling [2], I guess this is an "upstream" issue.
Feel free to re-open if you don't think so, bye 👋

---

* [1] : <https://www.freedesktop.org/software/systemd/man/os-release.html#VERSION_CODENAME=>
* [2] : <https://github.com/python-distro/distro/blob/c613bdfe2ae4f8b823e38376f537b1d07bac6bd3/distro.py#L1058-L1076>
