### ISSUE TITLE
Clarify that distro.version() can return an empty string in case of rolling distributions

### ISSUE THREAD

**Issue by jmetrius** [python-distro/distro#251]
I ran into an interesting bug while doing some testing on Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1609483).
Basically, if no version information is provided distro.version() returns an empty string and that was unexpected.
https://www.freedesktop.org/software/systemd/man/os-release.html states providing no version information is valid behaviour for rolling release distributions (such as Arch Linux), so I guess this is also acceptable behaviour for this package?
I was wondering if the documentation could be changed to reflect that.

**Comment by HorlogeSkynet** [comment]
From OS-RELEASE(5) documentation (as you pointed out) :

> Note that operating system vendors may choose not to provide version information, for example to accommodate for rolling releases. In this case, `VERSION` and `VERSION_ID` may be unset. Applications should not rely on these fields to be set.

---

@jmetrius You're right, contributions are welcome 🙂

**Comment by HorlogeSkynet** [comment]
Closing here as #312 is on its way.
