### ISSUE TITLE
distro.linux_distribution() is returning nothing on android (PyDroid)

### ISSUE THREAD

**Issue by RedSun-ops** [python-distro/distro#253]
distro.linux_distribution() is returning this : (' ', ' ', ' ')
:-1:

**Comment by ingrinder** [comment]
Further details on android:

* No `os-release` file (not even in `/usr/lib/os-release`)
* `lsb_release` not available
* No `/etc/.*(-|_)(version|release)` (distro release) file
* `uname` output not helpful, e.g. `Linux localhost 4.4.200-ga25afee7cf23 #1 SMP PREEMPT Tue Feb 18 22:10:04 UTC 2020 armv8l`

The *only* way I have found to reliably distinguish an Android environment is via the existence of `/system/bin/getprop`. `getprop ro.build.version.release` can be used to provide the version number of Android.

**Comment by sethmlarson** [comment]
Since this hasn't moved in 2 years and there isn't an easy solution I think it's unlikely to land. Can reopen if there's enough drive to work on this.
