### ISSUE TITLE
Command 'lsb_release -a' returned non-zero exit status 1

### ISSUE THREAD

**Issue by arossert** [python-distro/distro#260]
I have encountered an issue in a Linux server where the `lsb_release` command is broken.
I have researched a bit and it seems that it might happen on some ubuntu distributions (maybe also on others).
I think that this should be handled properly by ignoring errors on `lsb_release` execution.
I will submit a PR for a fix.

**Comment by brejoc** [comment]
I can confirm this observation. This also happens in OBS builds, where there is no `apt-cache` installed. See [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951651).

**Comment by HorlogeSkynet** [comment]
Actually fixed in #260, and released as v1.6.0, closing here.
