### ISSUE TITLE
Add guix in the list of distro IDs

### ISSUE THREAD

**Issue by akxs14** [python-distro/distro#303]
Can you please add 'guix' in the list of recognized Distro IDs? It should point to the GNU GUIX System.

**Comment by sethmlarson** [comment]
Part of adding a system is providing all `/etc/*-release` files and the output of `linux_distribution`, could you provide those? Otherwise this will likely not be completable by our team.

**Comment by brejoc** [comment]
@akxs14 On a related note: Maybe you could even open a PR at [higanworks/os_catalog](https://github.com/higanworks/os_catalog)!? But this is of course completely unrelated to getting Guix supported here. Would just be nice to also have it there.

**Comment by akxs14** [comment]
Thank you very much for the quick response @sethmlarson ! os-release is attached below (I added the extension *.txt so it can be attached in the message). 

[os-release.txt](https://github.com/python-distro/distro/files/6896937/os-release.txt)

The output of `linux_distribution` is  `('GNU', '', '')` . Please let me know if you need anything else.

**Comment by akxs14** [comment]
Very happy to do so @brejoc !

**Comment by akxs14** [comment]
Hi again @sethmlarson , would it help if I open a PR with the requested addition?

**Comment by sethmlarson** [comment]
@akxs14 Yes that'd be awesome!

**Comment by akxs14** [comment]
Ping @sethmlarson , @HorlogeSkynet 

https://github.com/python-distro/distro/pull/308
