### ISSUE TITLE
Add support for Rocky Linux

### ISSUE THREAD

**Issue by johnthagen** [python-distro/distro#320]
[Rocky Linux](https://rockylinux.org/) is the spiritual successor to CentOS now that [CentOS 8's lifetime was cut short and only CentOS Stream will continue](https://arstechnica.com/gadgets/2020/12/centos-shifts-from-red-hat-unbranded-to-red-hat-beta/).

**Comment by HorlogeSkynet** [comment]
Please see #321. Thanks :bow:
