### ISSUE TITLE
Can we detect base distribution with this module ?

### ISSUE THREAD

**Issue by 0ne-zero** [python-distro/distro#346]
I was wondering is there any way to detect base distribution of distro ?
I found base() method in issues but it seems has been removed #36 
If we can't do it now, why?

**Comment by HorlogeSkynet** [comment]
Hi @0ne-zero, if your distribution supports it, you can use `distro.like` method which is based on OS-RELEASE(5) `ID_LIKE` entry.
It may contain space-separated identifiers, specified by distribution maintainers.
Please tell us if this could help you.

**Comment by 0ne-zero** [comment]
Thank you, It was everything that i need.

**Comment by kdeldycke** [comment]
I addressed the issue of distribution families at: https://github.com/python-distro/distro/issues/221#issuecomment-4158763641
