### ISSUE TITLE
Documentation on readthedocs is still for version 1.3.0

### ISSUE THREAD

**Issue by lengau** [python-distro/distro#357]
It'd be nice if we could have the docs for v1.8.0 up there. Even if there aren't significant changes, it'd probably make people feel better about using those docs

**Comment by HorlogeSkynet** [comment]
Could you investigate Sphinx generation and publishing to RTD @jdufresne ? 🙂

**Comment by HorlogeSkynet** [comment]
Up @jdufresne :pray:
Maybe we could release v1.8.1 once documentation publication is fixed ?

Thanks, bye :wave:

**Comment by jdufresne** [comment]
@HorlogeSkynet Sorry, I will not have time investigate this. However, I took a quick peek and I don't appear to have access to the python-distro project on RTD. Maybe someone else is already the admin.

**Comment by HorlogeSkynet** [comment]
Thanks for your answer; @nir0s do you (still) have access to RTD ? :slightly_smiling_face:

**Comment by pritamvkulkarni** [comment]
Do we have any update on this?

**Comment by nir0s** [comment]
Hey. I'll check. I'm pretty sure I do.

Tbh, I'd move away from RTD and keep things documented in GitHub. It's such
a small library..

**Comment by HorlogeSkynet** [comment]
Little up @nir0s :slightly_smiling_face:

**Comment by pranavmarla** [comment]
FYI:
- The latest documentation can be found in the source code on GitHub: https://github.com/python-distro/distro/blob/master/docs/index.rst
- As mentioned above, the content on https://distro.readthedocs.io/ corresponds to v`1.3.0` of the source: https://github.com/python-distro/distro/blob/v1.3.0/docs/index.rst
