### ISSUE TITLE
Testcase for Pidora is missing

### ISSUE THREAD

**Issue by andy-maier** [python-distro/distro#82]
Pidora (ID: `pidora`) is one of the distros with a reliable ID. A testcase should be added.

If you want to help, it is sufficient to post to this issue:
- The content of the `/etc/os-release` file, if any.
- The file names and content of the `/etc/*release` and `/etc/*version` files, if any.
- The output of the command: `lsb_release -a`, if available.

**Comment by funkyfuture** [comment]
- Pidora (the OS) is [discontinued](https://distrowatch.com/table.php?distribution=pidora)
- nobody responded to this in five yeears

hence i propose to close the issue and accept test cases in a pull request.
