### ISSUE TITLE
Testcase for XenServer is missing

### ISSUE THREAD

**Issue by andy-maier** [python-distro/distro#85]
XenServer (ID: `xenserver`) is one of the distros with a reliable ID. A testcase should be added.

If you want to help, it is sufficient to post to this issue:
- The content of the `/etc/os-release` file, if any.
- The file names and content of the `/etc/*release` and `/etc/*version` files, if any.
- The output of the command: `lsb_release -a`, if available.

**Comment by funkyfuture** [comment]
- XenServer is [discontinued](https://web.archive.org/web/20210426172629/https://xenserver.org/)
- nobody responded to this in five years

hence i propose to close the issue and accept test cases in a pull request.
